Refactor generating random products
ICTM1l1/nerdygadgets pull request #10
Opened 2020-11-13 16:05 UTC by Wasstyr

2020-11-13 16:12 UTC, KoenvanMeijeren approved these changes

2020-11-13 18:48 UTC, KoenvanMeijeren approved these changes

2020-11-16 19:40 UTC, KoenvanMeijeren requested changes

2020-11-16 19:40 UTC, KoenvanMeijeren commented on Src/Crud/product.php
> + * @param int $productIds
Dit moet een array zijn.

2020-11-16 19:40 UTC, KoenvanMeijeren commented on Src/Crud/product.php
> +function getRandomProductForCatergory($productIds){
Type hint de parameter even d.m.v. voor de variabele de keyword 'array' te zetten --> `array $productIds`

2020-11-16 19:40 UTC, KoenvanMeijeren commented on Src/Crud/product.php
> +    return getRandomProductForCatergory($productIds);
Zorg er voor dat hij hier gewoon de ID's returnt. De taak van deze functie is dat hij de id's moet ophalen, niet het random selecteren van een product. Dat moet gebeuren in de functie `getRandomProductForCategory`. In die functie moet je dus `getProductForCategory` aan roepen.

2020-11-16 19:40 UTC, KoenvanMeijeren commented on Src/Crud/product.php
> +        return select("SELECT SI.StockItemID,
Deze select statement is een tabje te veel uitgelijnd. Zorg ervoor dat hij 1 tab naar links wordt gezet en daardoor op dezelfde hoogte komt als de for loop.

2020-11-16 19:40 UTC, KoenvanMeijeren commented on Src/Crud/product.php
> +function getProductForCategory(int $categoryID) {
Hernoem deze functie. Hij returnt geen producten maar de id's van producten. Daarnaast moet de functienaam in meervoud zijn omdat hij een array returnt. (meerdere values)

2020-11-17 12:37 UTC, J3fftw1 approved these changes
LGTM

2020-11-17 12:37 UTC, KoenvanMeijeren approved these changes

2020-11-17 12:38 UTC, KoenvanMeijeren approved these changes

2020-11-17 12:38 UTC, merged