Add related products to shopping cart page based on products in cart
ICTM1l1/nerdygadgets pull request #27
Opened 2020-11-26 13:18 UTC by Wasstyr

2020-11-26 14:08 UTC, KoenvanMeijeren requested changes

2020-11-26 14:08 UTC, KoenvanMeijeren commented on Public/shoppingcart.php
> +                ?> <br><h3>Gerelateerde Producten<h3/>
Waarom staat hier een `<br>` element?

2020-11-26 16:02 UTC, ikbenlike submitted a review, later dismissed

2020-11-27 14:19 UTC, KoenvanMeijeren approved these changes

2020-11-27 15:00 UTC, ikbenlike approved these changes

2020-11-27 15:00 UTC, merged