Feature/ts24 until ts35 bug fixes
ICTM1l1/nerdygadgets pull request #33
Opened 2020-12-03 12:11 UTC by KoenvanMeijeren

2020-12-03 13:30 UTC, Wasstyr approved these changes

2020-12-06 16:03 UTC, ikbenlike requested changes

2020-12-06 16:03 UTC, ikbenlike commented on Src/Core/Cart.php
> +            add_user_message('Product aantal is succesvol bijgewerkt.');
in het FO staat niet dat hier een melding voor getoond moet worden

2020-12-06 16:03 UTC, ikbenlike commented on Src/Core/Cart.php
> +            add_user_message('Product is succesvol verwijderd uit de winkelwagen.');
in het FO staat niet dat hiervoor een melding getoond moet worden

2020-12-06 16:03 UTC, ikbenlike commented on Src/Core/Cart.php
> +            add_user_message('Product aantal is succesvol bijgewerkt.');
in het FO staat niet dat hiervoor een melding getoond moet worden

2020-12-06 20:22 UTC, KoenvanMeijeren commented
Ik heb al die meldingen verplaatst naar de cart class, zodat er op 1 plek de meldingen gegenereerd kunnen worden. Dat zorgt ook voor consistentie.

Hij wijkt nu idd af van het ontwerp. Daar worden pop-ups getoond en wij doen meldingen. Ik vind dat beter en gebruiksvriendelijker, wat jij? 

De overige meldingen voor de acties staan idd niet in het FO, maar ik zou ze daar ook willen toevoegen. Dat zorgt voor betere terugkoppeling naar de gebruikers en dus ook voor meer gebruiksvriendelijkheid. Wat vind jij?

Ik kan dit eventueel dinsdag wel gaan aanpassen, maar anders wil ik dit na de einddemo gaan recht trekken.

2020-12-07 04:30 UTC, ikbenlike commented
ik zeg dat het in het FO aanpassen

2020-12-07 04:30 UTC, ikbenlike approved these changes

2020-12-07 04:30 UTC, merged